### ISSUE TITLE
Key generation with bash

### ISSUE THREAD

**Issue by ColonelThirtyTwo** [ahester57/ipfs-private-swarm#1]
```
(echo -e '/key/swarm/psk/1.0.0/\n/base16/' ; head -c 32 /dev/urandom | od -t x1 -A none - | tr -d '\n '; echo '') > /tmp/test.key
```

In case you don't want to download go to run a 10 line go script.

**Comment by ATikadze** [comment]
Thank you 🙌

**Comment by ahester57** [comment]
Thanks @ColonelThirtyTwo for the suggestion. I have added it as an alternative method of generating the `swarm.key`
